---
version: 2.1

executors:
  docker_stable:
    docker:
      - image: 'docker:stable'
  docker_terraform:
    docker:
      - image: 'hashicorp/terraform:0.12.25'
    resource_class: 'small'
    shell: /bin/sh -leo pipefail

orbs:
  aws-ecr: circleci/aws-ecr@6.9.1

aliases:
  # git branches filters
  - &except_master_branch
    filters:
      branches:
        ignore: master
  - &only_master_branch
    filters:
      branches:
        only: master


jobs:

  build:
    executor: docker_terraform
    working_directory: '~/repo'
    steps:
      - checkout
      - run:
          name: build | install apk packages
          command: sh .circleci/install-apk-packages.sh
      - run:
          name: build | set env variables
          command: |
            cd terraform/
            echo -e "key=${CI_ENVIRONMENT}/${AWS_REGION}/applications.tfstate"
            echo -e "bucket=eks-asg-tests"
            echo -e "region=${AWS_DEFAULT_REGION}"
            echo -e "state_bucket_key=${CI_ENVIRONMENT}/${AWS_REGION}/aws_infra.tfstate"
            terraform init \
              -backend-config="key=${CI_ENVIRONMENT}/${AWS_REGION}/applications.tfstate" \
              -backend-config="bucket=${CIRCLE_PROJECT_REPONAME}" \
              -backend-config="region=${AWS_DEFAULT_REGION}"
            terraform refresh \
              -var="state_bucket=${CIRCLE_PROJECT_REPONAME}" \
              -var="state_bucket_key=${CI_ENVIRONMENT}/${AWS_REGION}/aws_infra.tfstate" \
              -var="state_region=${AWS_DEFAULT_REGION}"
            export AWS_ECR_ACCOUNT_URL=$(terraform output ecr_registry_url)
            export AWS_ECR_REPONAME=$(terraform output ecr_repository_name)
      - aws-ecr/build-and-push-image: # https://circleci.com/orbs/registry/orb/circleci/aws-ecr
          account-url: AWS_ECR_ACCOUNT_URL
          aws-access-key-id: AWS_ACCESS_KEY_ID
          aws-secret-access-key: AWS_SECRET_ACCESS_KEY
          no-output-timeout: 3m
          path: apps/nginx-hello/
          region: AWS_REGION
          repo: ${AWS_ECR_REPONAME}
          tag: latest,${CIRCLE_SHA1}


workflows:
  eks-prod:
    jobs:
      - build:
          context: env-prod
          <<: *only_master_branch

  eks-staging:
    jobs:
      - build:
          context: env-staging
          <<: *except_master_branch
