---
version: 2.1

executors:
  docker_stable:
    docker:
      - image: 'docker:stable'
    resource_class: 'small'


aliases:
  # git branches filters
  - &except_master_branch
    filters:
      branches:
        ignore: master
  - &only_master_branch
    filters:
      branches:
        only: master


orbs:
  aws-eks: circleci/aws-eks@0.2.7
  kubernetes: circleci/kubernetes@0.11.0


jobs:

  deploy_apps:
    executor: docker_stable
    working_directory: '~/repo'
    environment:
      BASH_ENV: /etc/profile
      TERRAFORM_VERSION: 0.12.25
      CIRCLE_INFRA_PROJECT_REPONAME: eks-asg-tests
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: build | install apk packages
          command: sh .circleci/install-apk-packages.sh
      - kubernetes/install
      - aws-eks/install-eksctl
      - aws-eks/update-kubeconfig-with-authenticator:
          aws-region: "${AWS_REGION}"
          cluster-name: "${CIRCLE_INFRA_PROJECT_REPONAME}"
      - run:
          name: build | set env variables
          command: |
            cd terraform/
            terraform init \
              -backend-config="key=${CI_ENVIRONMENT}/${AWS_REGION}/applications.tfstate" \
              -backend-config="bucket=${CIRCLE_INFRA_PROJECT_REPONAME}" \
              -backend-config="region=${AWS_DEFAULT_REGION}"
            terraform refresh \
              -var="state_bucket=${CIRCLE_INFRA_PROJECT_REPONAME}" \
              -var="state_bucket_key=${CI_ENVIRONMENT}/${AWS_REGION}/aws_infra.tfstate" \
              -var="state_region=${AWS_DEFAULT_REGION}" \
              -var="commit_sha1=${CIRCLE_SHA1}"
            echo "export AWS_ECR_ACCOUNT_URL=$(terraform output ecr_registry_url)" >> $BASH_ENV
            echo "export AWS_ECR_REPONAME=$(terraform output ecr_repository_name)" >> $BASH_ENV
            source $BASH_ENV
      - run:
          name: build | login in repo
          command: |
            aws ecr get-login-password --region ${AWS_REGION} | \
            docker login --username AWS --password-stdin ${AWS_ECR_ACCOUNT_URL}
      - run:
          name: build | build app [nginx-hello]
          command: |
            cd apps/nginx-hello
            docker build -f Dockerfile -t "$AWS_ECR_ACCOUNT_URL:$CIRCLE_SHA1" .
      - run:
          name: build | push app [nginx-hello]
          command: docker push ${AWS_ECR_ACCOUNT_URL}:${CIRCLE_SHA1}
      - run:
          name: build | deploy app [nginx-hello]
          command: |
            cd terraform/
            terraform apply \
              -auto-approve \
              -lock=true \
              -input=false \
              -lock-timeout=30s \
              -refresh=true \
              .



workflows:
  eks-prod:
    jobs:
      - deploy_apps:
          context: env-prod
          <<: *only_master_branch

  eks-staging:
    jobs:
      - deploy_apps:
          context: env-staging
          <<: *except_master_branch
