---
version: 2.1

executors:
  docker_stable:
    docker:
      - image: 'docker:stable'
    resource_class: 'small'
  docker_terraform:
    docker:
      - image: 'hashicorp/terraform:0.12.25'
    resource_class: 'small'
    shell: /bin/sh -leo pipefail

orbs:
  aws-ecr: circleci/aws-ecr@6.9.1

aliases:
  # git branches filters
  - &except_master_branch
    filters:
      branches:
        ignore: master
  - &only_master_branch
    filters:
      branches:
        only: master


jobs:

  build:
    executor: docker_stable
    working_directory: '~/repo'
    environment:
      BASH_ENV: /etc/profile
      TERRAFORM_VERSION: 0.12.25
      CIRCLE_INFRA_PROJECT_REPONAME: eks-asg-tests
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: build | install apk packages
          command: sh .circleci/install-apk-packages.sh
      - run:
          name: build | set env variables
          command: |
            cd terraform/
            terraform init \
              -backend-config="key=${CI_ENVIRONMENT}/${AWS_REGION}/applications.tfstate" \
              -backend-config="bucket=${CIRCLE_INFRA_PROJECT_REPONAME}" \
              -backend-config="region=${AWS_DEFAULT_REGION}"
            terraform refresh \
              -var="state_bucket=${CIRCLE_INFRA_PROJECT_REPONAME}" \
              -var="state_bucket_key=${CI_ENVIRONMENT}/${AWS_REGION}/aws_infra.tfstate" \
              -var="state_region=${AWS_DEFAULT_REGION}"
            echo "export AWS_ECR_ACCOUNT_URL=$(terraform output ecr_registry_url)" >> $BASH_ENV
            echo "export AWS_ECR_REPONAME=$(terraform output ecr_repository_name)" >> $BASH_ENV
      - run:
          name: build | login in repo
          command: |
            source $BASH_ENV
            aws ecr get-login-password --region ${AWS_REGION} | \
            docker login --username AWS --password-stdin ${AWS_ECR_ACCOUNT_URL}
      - run:
          name: build | nginx-hello
          command: |
            source $BASH_ENV
            cd apps/nginx-hello
            docker build -f Dockerfile -t "$AWS_ECR_ACCOUNT_URL:$CIRCLE_SHA1" .
      - run:
          name: build | push nginx-hello
          command: |
            source $BASH_ENV
            docker push ${AWS_ECR_ACCOUNT_URL}:${CIRCLE_SHA1}


workflows:
  eks-prod:
    jobs:
      - build:
          context: env-prod
          <<: *only_master_branch

  eks-staging:
    jobs:
      - build:
          context: env-staging
          <<: *except_master_branch
