apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: nginx-manifest
  name: nginx-manifest
  namespace: apps
spec:
  progressDeadlineSeconds: 600
  replicas: 2
  selector:
    matchLabels:
      app: nginx-manifest
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: nginx-manifest
    spec:
      containers:
      - image: 476148382817.dkr.ecr.us-east-2.amazonaws.com/eks-asg-tests:519c0f8564692f0a54ce58fd1b260a18cbc3926b
        imagePullPolicy: IfNotPresent
        name: nginx-manifest
        resources:
          limits:
            cpu: 500m
            memory: 128Mi
          requests:
            cpu: 200m
            memory: 50Mi
      dnsPolicy: ClusterFirst
      terminationGracePeriodSeconds: 30

---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: nginx-manifest
  name: nginx-manifest
  namespace: apps
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: nginx-manifest
  sessionAffinity: ClientIP
  sessionAffinityConfig:
    clientIP:
      timeoutSeconds: 10800
  type: ClusterIP

---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: nginx-manifest
  namespace: apps
spec:
  backend:
    serviceName: nginx-manifest
    servicePort: 80
  rules:
  - http:
      paths:
      - backend:
          serviceName: nginx-manifest
          servicePort: 80
        path: /nginx1
