apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.app.name | quote }}
  labels:
    helm.sh/chart: {{ .Values.app.name | quote }}
    app.kubernetes.io/name: {{ .Chart.Name }}-{{ .Chart.appVersion }}
    app.kubernetes.io/instance: {{ .Values.app.name | quote }}
    app.kubernetes.io/version: {{ .Chart.Version }}
    app.kubernetes.io/managed-by: Helm
spec:
  progressDeadlineSeconds: 600
  replicas: {{ .Values.app.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.app.name | quote }}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
  template:
    metadata:
      labels:
        app: {{ .Values.app.name | quote }}
    spec:
      containers:
      - image: {{ .Values.container.image }}
        imagePullPolicy: IfNotPresent
        name: {{ .Values.app.name | quote }}
        resources:
          limits:
            cpu: 250m
            memory: 100Mi
          requests:
            cpu: 100m
            memory: 50Mi
      dnsPolicy: ClusterFirst
      terminationGracePeriodSeconds: 30
