{{- $serviceName := .Values.app.name }}
{{- $servicePort := .Values.app.service.port -}}
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ .Values.app.name }}
spec:
  backend:
    serviceName: {{ .Values.app.name }}
    servicePort: {{ .Values.app.service.port }}
  rules:
  {{- range .Values.app.ingress.hosts }}
    {{- $url := splitList "/" . }}
    - host: {{ first $url }}
      http:
        paths:
        - backend:
            serviceName: {{ $serviceName }}
            servicePort: {{ $servicePort }}
          path: /{{ rest $url | join "/" }}
  {{- end }}
  {{- if .Values.app.ingress.tls }}
  tls:
{{ toYaml .Values.app.ingress.tls | indent 4 }}
  {{ end -}}